### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by amirjaufeeraully** [antoinelabard/skype_flutter_clone#1]
Can you help?

**Comment by antoinelabard** [comment]
Can you describe the problem you're facing ?

**Comment by boubou19** [comment]
> Can you help?

Don't expect any dev to help you if you don't provide logs/errors/any useful resource so the dev can diagnose/fix the error. Otherwise it's just finding a needle in a haystack. No sane dev like searching for needles in a haystack 😄
